--------------------------------------------------------
--  Constraints for Table PROGRESS
--------------------------------------------------------

  ALTER TABLE "ARGUS"."PROGRESS" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."PROGRESS" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."PROGRESS" MODIFY ("RECORDBOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."PROGRESS" MODIFY ("SEMESTR_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."PROGRESS" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
