--------------------------------------------------------
--  Ref Constraints for Table PROGRESS
--------------------------------------------------------

  ALTER TABLE "ARGUS"."PROGRESS" ADD CONSTRAINT "PROGRESS_CON_FK_REPORT_ID" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "ARGUS"."REPORT" ("REPORT_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."PROGRESS" ADD CONSTRAINT "PROGRESS_CON_FK_SUBJ_ID" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "ARGUS"."SUBJECT" ("SUBJECT_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."PROGRESS" ADD CONSTRAINT "PROGRESS_CON_FK_RB_ID" FOREIGN KEY ("RECORDBOOK_ID")
	  REFERENCES "ARGUS"."STUDENT" ("RECORDBOOK_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."PROGRESS" ADD CONSTRAINT "PROGRESS_CON_FK_SEM_ID" FOREIGN KEY ("SEMESTR_ID")
	  REFERENCES "ARGUS"."SEMESTR" ("SEMESTR_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."PROGRESS" ADD CONSTRAINT "PROGRESS_CON_TCHR_ID" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "ARGUS"."TEACHER" ("TEACHER_ID") ON DELETE SET NULL ENABLE;
