REM INSERTING into ARGUS.SEMESTR
SET DEFINE OFF;
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (1,'²');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (2,'²²');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (3,'²²²');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (4,'IV');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (5,'V');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (6,'VI');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (7,'VII');
Insert into ARGUS.SEMESTR (SEMESTR_ID,SEMESTR_NAME) values (8,'VIII');
