--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "ARGUS"."STUDENT" MODIFY ("RECORDBOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."STUDENT" MODIFY ("S_PASS" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."STUDENT" MODIFY ("N_PASS" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."STUDENT" MODIFY ("DATA_PASS" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."STUDENT" MODIFY ("NAME_DEPT_PASS" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("RECORDBOOK_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ARGUS"."STUDENT" ADD CONSTRAINT "STUDENT_CON" UNIQUE ("INN")
  USING INDEX  ENABLE;
