REM INSERTING into ARGUS.SUBJECT
SET DEFINE OFF;
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (2,'Організація баз даних','ОБД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (3,'Комп''ютерні мережі','КМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (4,'Захист розподілених баз даних та інформаційних систем','ЗРБДтаІС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (5,'Безпека та захист операційних систем','БЗОС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (1,'Вища математика','ВМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (6,'    Аналіз випадкових процесів','АВП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (7,'    Архітектура програмних систем захисту інформації','АПСЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (8,'    Архітектура систем захисту інформації (КСЗІ)','АСЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (9,'    Архітектура та проектування програмного забезпечення','АППЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (10,'    Безпека Web-додатків','БWД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (11,'    Безпека програм та даних','БПД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (12,'    Безпека систем передачі даних','БСПД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (15,'    Використання технологій нечіткої логіки та нейронних мереж ','ВТНЛНМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (16,'    Вступ до програмування .NET та JAVA','ВПJ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (17,'    Генетичні алгоритми','ГА');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (18,'    Гетерогенні і відкриті системи','ГВС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (19,'    Гіпермедійні системи навчання та тестування','ГСНТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (20,'    Дискретна математика','ДМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (21,'    Дискретний аналіз','ДА');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (22,'    Дискретні структури і алгоритми','ДСА');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (23,'    Додаткові розділи комбінаторного аналізу','ДРКА');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (24,'    Емпіричні методи кібербезпеки','ЕМК');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (25,'    Емпіричні методи програмної інженерії','ЕМПІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (26,'    Засоби програмування комп''ютерної графіки','ЗПКГ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (27,'    Засоби та методи аналізу захищеності програм','ЗМАЗП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (28,'    Захист експериментальних даних','ЗЕД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (29,'    Захист комп''ютерних мереж','ЗКМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (30,'    Захист операційних систем','ЗОС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (31,'    Захист програмних реалізацій','ЗПР');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (33,'    Захист інформації в розподілених системах','ЗІРС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (34,'    Інструментальні пакети керування інформаційною безпекою','ІПКІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (35,'    Інтелектуальний аналіз в мережі Internet','ІАМІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (36,'    Інтелектуальний аналіз даних','ІАД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (37,'    Інтелектуальні агенти і агентні системи','ІААС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (38,'    Інтелектуальні алгоритми інформаційного пошуку','ІАІП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (39,'    Інтелектуальні технології в Internet і Semantic Web','ІТІСВ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (40,'    Internet-технології','ІІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (41,'    Інтернет технології в навчанні','ІТН');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (42,'    Інформатика та програмування','ІП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (43,'    Інформатика','І');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (44,'    Інформаційна безпека спеціалізованих систем','ІБСС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (45,'    Інформаційна безпека','ІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (46,'    Інформаційно-комп''ютерні технології','ІКТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (47,'    Інформаційні інтернет-технології','ІІТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (48,'    Керування ризиками інформаційної безпеки','КРІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (49,'    Когнітивне моделювання','КМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (50,'    Комбінаторні методи захисту інформації','КМЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (51,'    Комп''ютерна графіка в маркетингу','КГМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (52,'    Комп''ютерна обробка графічних','КОГ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (53,'    Комп''ютерна обробка зображень','КОЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (54,'    Комп''ютерний синтез та обробка зображень','КСОЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (55,'    Комп''ютерні технології та програмування. Частина 1','КТП-1');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (56,'    Комп''ютерні технології та програмування. Частина 2','КТП-2');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (57,'    Компонентне програмування','КП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (58,'    Конструювання програмного забезпечення','КОП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (59,'    Криптографічні протоколи','КрП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (60,'    Крос-платформне програмування','КОП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (61,'    Логіка в системах штучного інтелекту','ЛСШІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (62,'    Математичне програмування','МП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (63,'    Математичні методи дослідження операцій','ММОП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (64,'    Математичні методи криптографії','ММК');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (65,'    Математичні основи теорії систем','МОТС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (66,'    Математичні основи теорії ігор','МОТІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (67,'    Менеджмент проектів програмного забезпечення','МППЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (68,'    Мережні інформаційні технології','МІТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (69,'    Метаевристичні методи та глибоке навчання','ММГН');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (70,'    Методи аналізу даних','МАД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (71,'    Методи графічного скриття інформації','МГСІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (72,'    Методи комп''ютерної обробки соціологічної інформації','МКОСІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (73,'    Методи прийняття проектних рішень','МППР');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (74,'    Методи приховування інформації','МПІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (75,'    Методи проектування трансляторів','МПТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (76,'    Методи та засоби криптографічного захисту інформації','МСКЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (77,'    Методи та засоби обробки текстової інформації','МЗОТІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (78,'    Методи та засоби розподілених даних та систем','МЗРДС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (79,'    Методи та засоби технічного захисту інформації','МЗТЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (80,'    Методи та системи штучного інтелекту','МСШІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (81,'    Мови та системи імітаційного моделювання','МСІМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (82,'    Моделювання систем','МС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (83,'    Моніторинг безпеки функціонування ІКС та комп''ютерних мереж','МБМІКСКМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (84,'    Мультиагентні інтелектуальні інформаційні системи','МІІС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (85,'    Нейронні мережі та комп''ютерна графіка ','НМКГ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (86,'    Нейронні мережі','НМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (87,'    Нормативна база інформаційної безпеки','НБІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (88,'    Об''єктно-орієнтоване програмування','ООП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (89,'    Операційні системи','ОС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (90,'    Організація баз даних та знань','ОБДЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (92,'    Основи web-програмування','ОВП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (93,'    Основи актуарних обчислень','ОАБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (94,'    Основи алгоритмізації','ОАБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (95,'    Основи безпеки в Інтернет','ОБІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (96,'    Основи захисту інформації','ОЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (97,'    Основи проектування систем розпізнавання образів','ОАСРО');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (98,'    Основи стеганографічних перетворень','ОСП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (99,'    Основи інформатики та комп''ютерної техніки','ОІКТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (100,'    Основи інформаційної безпеки','ОІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (101,'    Паралельні інформаційні системи','ПІС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (102,'    Програмне забезпечення економічних розрахунків','ПЗЕР');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (103,'    Програмне забезпечення мережевих технологій','ПЗМТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (104,'    Програмне забезпечення','ПЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (105,'    Програмне моделювання динамічних процесів','ПМДП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (106,'    Програмно-апаратні комплекси захисту інформації (КСЗІ)','ПАКЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (107,'    Програмування в Інтернет','ПвІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (108,'    Програмування мобільних та вбудованих пристроїв','ПМВП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (109,'    Програмування систем з серверами баз даних','ПССБД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (110,'    Програмування','П');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (111,'    Проектні рішення у кібербезпеці','ПРК');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (112,'    Проектування інформаційних систем','ПІС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (113,'    Професійна практика програмної інженерії','ПППІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (114,'    Розпізнавання зображень','РЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (115,'    Сервіс-орієнтована архітектура інформаційних управляючих систем','СОАІУС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (116,'    Системи технічного захисту інформації','СТЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (117,'    Системний аналіз та моделювання систем','САМС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (118,'    Системний аналіз та проектування','САП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (119,'    Спеціалізовані мови та технології програмування','СМТП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (120,'    Стандартизація і сертифікація в галузі IT','ССІТ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (121,'    Статистичні методи оцінювання','СМО');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (122,'    Стеганографічні методи захисту інформації','СМЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (123,'    Сучасне наукове дослідження: організація','СНД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (124,'    Сучасні засоби інформатики та комп''ютерний ринок','СЗІКР');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (125,'    Сучасні технології програмування','СТП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (126,'    Сучасні технології та системи візуального віртуального моделювання','СТСВРМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (127,'    Теорія алгоритмів','ТА');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (128,'    Теорія графів та комбінаторика','ТГК');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (129,'    Теорія прийняття рішень','ТПР');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (130,'    Теорія синтаксичного аналізу і компіляції','ТСАК');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (131,'    Теорія та організація розподіленої обробки даних','ТОРОД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (132,'    Теорія та практика комп''ютерних експериментів PhD ','ТПКЕ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (133,'    Технологія створення програмних продуктів','ТСПП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (134,'    Технології захисту інформації','ТЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (135,'    Технології й сервіси мережі Інтернет та SOA','ТСМІSOA');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (136,'    Технології комп''ютерного проектування','ТКП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (137,'    Технології розподілених систем та паралельних обчислень','ТРСПО');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (138,'    Технології розробки та супроводження Інтернет-сайтів','ТРПІС');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (139,'    Технології розробки та тестування програмного забезпечення','ТРТПЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (140,'    Технології створення веб-застосувань','ТСВЗ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (141,'    Технології створення криптографічних додатків','ТСКД');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (142,'    Технічні та алгоритмічні системи захисту інформації','ТАСЗІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (143,'    Управління інформаційною безпекою','УІБ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (144,'    Управління ІТ-проектами','УІТІ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (145,'    Функціональне та логічне програмування','ФЛП');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (146,'    Хмарні (Cloudy-) технології','ХМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (147,'    Цифрова обробка та розпізнавання мови','ЦОРМ');
Insert into ARGUS.SUBJECT (SUBJECT_ID,SUBJECT_NAME,SUBJECT_BR_NAME) values (148,'    Чисельні методи	','ЧМ');
