--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "ARGUS"."SUBJECT" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARGUS"."SUBJECT" ADD CONSTRAINT "SUBJECT_CON_SN_U" UNIQUE ("SUBJECT_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ARGUS"."SUBJECT" ADD CONSTRAINT "SUBJECT_CON_PK" PRIMARY KEY ("SUBJECT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ARGUS"."SUBJECT" MODIFY ("SUBJECT_BR_NAME" NOT NULL ENABLE);
