REM INSERTING into ARGUS.TEACHER
SET DEFINE OFF;
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (142,'МАЗУР ВОЛОДИМИР ІВАНОВИЧ','Кафедра ЕТ','Професор',to_date('11-APR-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (143,'МАРЧЕНКО МИКОЛА ПЕТРОВИЧ','Кафедра ЕТ','Старший викладач',to_date('18-SEP-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (144,'МЕЛЬНИК ВАСИЛЬ СТЕПАНОВИЧ','Кафедра ЕТ','Асистент',to_date('03-JUL-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (145,'МЕЛЬНИК ВІКТОР ПЕТРОВИЧ','Кафедра ПМІ','Доцент',to_date('11-MAY-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (146,'МЕЛЬНИК СЕРГІЙ ПЕТРОВИЧ','Кафедра ПМІ','Професор',to_date('26-JUN-05','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (147,'МОСКАЛЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПМІ','Старший викладач',to_date('03-SEP-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (148,'МОСКАЛЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ПМІ','Асистент',to_date('27-AUG-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (149,'ПАНЧЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ПМІ','Доцент',to_date('06-FEB-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (150,'ПОЛІЩУК АНАТОЛІЙ ІВАНОВИЧ','Кафедра ПМІ','Професор',to_date('11-SEP-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (151,'ПОЛІЩУК ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра ПМІ','Старший викладач',to_date('31-DEC-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (152,'ПОЛІЩУК ОЛЕКСАНДР ПЕТРОВИЧ','Кафедра ПМІ','Асистент',to_date('14-OCT-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (153,'ПОПОВ ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ПМІ','Доцент',to_date('06-JUN-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (154,'РОМАНЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПМІ','Професор',to_date('19-JUL-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (155,'РОМАНЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ПМІ','Старший викладач',to_date('23-AUG-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (156,'САВЧЕНКО ВАСИЛЬ ІВАНОВИЧ','Кафедра ПМІ','Асистент',to_date('04-APR-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (157,'САВЧУК ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра ПМІ','Доцент',to_date('19-APR-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (158,'СИДОРЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра ПМІ','Професор',to_date('11-JUL-15','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (159,'ТИЩЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ПМІ','Старший викладач',to_date('24-SEP-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (160,'ТИЩЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ПМІ','Асистент',to_date('22-APR-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (161,'ХОМЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра ПМІ','Доцент',to_date('02-MAY-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (162,'ШЕВЧУК МИХАЙЛО ІВАНОВИЧ','Кафедра ПМІ','Професор',to_date('11-APR-23','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (163,'БІЛОУС ВАСИЛЬ ІВАНОВИЧ','Кафедра ПМІ','Старший викладач',to_date('16-APR-05','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (164,'БОНДАР АНАТОЛІЙ ІВАНОВИЧ','Кафедра ПМІ','Асистент',to_date('14-JAN-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (165,'ВОЛОШИН ІВАН ІВАНОВИЧ','Кафедра ПМІ','Доцент',to_date('03-JAN-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (166,'ГОНЧАРЕНКО ВАСИЛЬ ІВАНОВИЧ','Кафедра ПМІ','Професор',to_date('19-OCT-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (167,'ГУМЕНЮК ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПМІ','Старший викладач',to_date('13-JAN-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (168,'ДІДЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ПМ','Асистент',to_date('16-SEP-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (169,'ІВАНОВ СЕРГІЙ ОЛЕКСАНДРОВИЧ','Кафедра ПМ','Доцент',to_date('13-OCT-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (170,'КАРПЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПМ','Професор',to_date('07-SEP-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (171,'КЛИМЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра ПМ','Старший викладач',to_date('13-JUL-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (172,'КОВАЛЕНКО ВІКТОР ВОЛОДИМИРОВИЧ','Кафедра ПМ','Асистент',to_date('18-JUN-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (173,'КОВАЛЕНКО МИКОЛА ПАВЛОВИЧ','Кафедра ПМ','Доцент',to_date('11-JUL-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (174,'КОВАЛЕНКО МИХАЙЛО ІВАНОВИЧ','Кафедра ПМ','Професор',to_date('31-OCT-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (175,'КОВАЛЕНКО ОЛЕКСАНДР ГРИГОРОВИЧ','Кафедра ПМ','Старший викладач',to_date('19-FEB-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (176,'КОВАЛЕНКО ЮРІЙ МИКОЛАЙОВИЧ','Кафедра ПМ','Асистент',to_date('21-MAY-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (177,'КОВАЛЬ ВАСИЛЬ МИХАЙЛОВИЧ','Кафедра ПМ','Доцент',to_date('23-OCT-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (178,'КОВАЛЬ МИХАЙЛО ВАСИЛЬОВИЧ','Кафедра ПМ','Професор',to_date('14-FEB-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (179,'КОВАЛЬОВ ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ПМ','Старший викладач',to_date('29-SEP-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (180,'КОВАЛЬЧУК АНАТОЛІЙ МИКОЛАЙОВИЧ','Кафедра ПМ','Асистент',to_date('26-AUG-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (181,'КОЛОМІЄЦЬ ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПМ','Доцент',to_date('29-JAN-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (182,'КОЛОМІЄЦЬ МИКОЛА МИКОЛАЙОВИЧ','Кафедра ПМ','Професор',to_date('25-NOV-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (183,'КОСТЮК МИКОЛА ІВАНОВИЧ','Кафедра ПМ','Старший викладач',to_date('20-SEP-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (184,'КРАВЧЕНКО МИКОЛА ОЛЕКСАНДРОВИЧ','Кафедра ПМ','Асистент',to_date('16-SEP-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (185,'КУЗЬМЕНКО АНАТОЛІЙ ІВАНОВИЧ','Кафедра ПМ','Доцент',to_date('20-SEP-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (186,'ЛЕВЧЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ХТХМ','Професор',to_date('20-AUG-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (187,'ЛИСЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ХТХМ','Старший викладач',to_date('31-JUL-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (188,'ЛИСЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра ХТХМ','Асистент',to_date('13-FEB-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (189,'ЛИТВИНЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ХТХМ','Доцент',to_date('25-OCT-18','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (190,'ЛИТВИНЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ХТХМ','Професор',to_date('29-SEP-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (191,'ЛУЦЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ХТХМ','Старший викладач',to_date('28-JAN-08','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (192,'МАРЧЕНКО АНАТОЛІЙ МИКОЛАЙОВИЧ','Кафедра ХТХМ','Асистент',to_date('21-SEP-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (193,'МАРЧЕНКО ОЛЕКСАНДР ВАСИЛЬОВИЧ','Кафедра ХТХМ','Доцент',to_date('24-MAY-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (194,'МЕЛЬНИК ІВАН ПЕТРОВИЧ','Кафедра ХТХМ','Професор',to_date('30-AUG-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (195,'МЕЛЬНИК МИХАЙЛО МИХАЙЛОВИЧ','Кафедра ХТХМ','Старший викладач',to_date('30-SEP-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (196,'МІЩЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ХТХМ','Асистент',to_date('23-JUN-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (197,'МОРОЗ ІВАН ІВАНОВИЧ','Кафедра ХТХМ','Доцент',to_date('16-MAR-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (198,'НАЗАРЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ХТХМ','Професор',to_date('26-APR-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (199,'ОЛІЙНИК МИКОЛА ПЕТРОВИЧ','Кафедра ХТХМ','Старший викладач',to_date('23-OCT-92','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (200,'ПАВЛЮК ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра ХТХМ','Асистент',to_date('02-MAR-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (201,'ПАВЛЮК МИКОЛА ІВАНОВИЧ','Кафедра ХТХМ','Доцент',to_date('11-AUG-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (202,'ПЕТРЕНКО ІВАН ІВАНОВИЧ','Кафедра ХТХМ','Професор',to_date('10-JUL-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (203,'ПРИХОДЬКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ВМіФ','Старший викладач',to_date('28-APR-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (204,'ПРИХОДЬКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ВМіФ','Асистент',to_date('31-AUG-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (205,'ПРОКОПЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ВМіФ','Доцент',to_date('11-JUL-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (206,'СИДОРЕНКО ВАСИЛЬ ІВАНОВИЧ','Кафедра ВМіФ','Професор',to_date('26-DEC-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (207,'СИДОРЕНКО МИКОЛА ВАСИЛЬОВИЧ','Кафедра ВМіФ','Старший викладач',to_date('30-AUG-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (6,'Слюнько Федір Вікторович','Кафедра АТ','Асистент',to_date('09-JAN-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (7,'Кукушкінд Фелікс Елізондович','Кафедра АТ','Доцент',to_date('09-JAN-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (8,'Сльопін Марк Андрійович','Кафедра ЕТ','Професор',to_date('09-JAN-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (9,'Кроніна Ольга Дмитрівна','Кафедра ЕТ','Доцент',to_date('09-JAN-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (208,'СИДОРЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ВМіФ','Асистент',to_date('14-NOV-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (209,'ТАРАСЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ВМіФ','Доцент',to_date('08-JAN-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (210,'ТЕРЕЩЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ВМіФ','Професор',to_date('09-AUG-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (211,'ТКАЧЕНКО ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра ВМіФ','Старший викладач',to_date('11-MAR-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (212,'ТКАЧЕНКО ОЛЕКСІЙ ІВАНОВИЧ','Кафедра ВМіФ','Асистент',to_date('07-MAR-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (213,'ТКАЧЕНКО СЕРГІЙ ВАСИЛЬОВИЧ','Кафедра ВМіФ','Доцент',to_date('01-JAN-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (214,'ТКАЧУК МИКОЛА МИКОЛАЙОВИЧ','Кафедра ВМіФ','Професор',to_date('17-MAR-18','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (215,'ФЕСЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ВМіФ','Старший викладач',to_date('01-NOV-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (216,'ХАРЧЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ВМіФ','Асистент',to_date('07-JUN-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (217,'ШЕВЧЕНКО ГРИГОРІЙ МИКОЛАЙОВИЧ','Кафедра ВМіФ','Доцент',to_date('08-NOV-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (218,'ШЕВЧУК АНАТОЛІЙ ІВАНОВИЧ','Кафедра ВМіФ','Професор',to_date('15-NOV-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (219,'ШЕВЧУК ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра ВМіФ','Старший викладач',to_date('04-JUN-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (220,'ШЕВЧУК ОЛЕКСАНДР ВОЛОДИМИРОВИЧ','Кафедра ВМіФ','Асистент',to_date('22-FEB-23','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (221,'ШЕВЧУК ОЛЕКСАНДР ПЕТРОВИЧ','Кафедра ВМіФ','Доцент',to_date('21-NOV-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (222,'АНТОНЮК ВАСИЛЬ ІВАНОВИЧ','Кафедра МП','Професор',to_date('19-AUG-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (223,'БОЙКО ВАСИЛЬ МИХАЙЛОВИЧ','Кафедра МП','Старший викладач',to_date('16-MAY-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (224,'БОЙКО ІВАН МИХАЙЛОВИЧ','Кафедра МП','Асистент',to_date('27-OCT-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (225,'БОЙКО СЕРГІЙ ОЛЕКСАНДРОВИЧ','Кафедра МП','Доцент',to_date('23-JUN-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (226,'БОНДАР ІВАН ІВАНОВИЧ','Кафедра МП','Професор',to_date('06-JAN-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (227,'БОНДАР ОЛЕКСАНДР ВОЛОДИМИРОВИЧ','Кафедра МП','Старший викладач',to_date('06-NOV-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (228,'БОНДАРЕНКО ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра МП','Асистент',to_date('22-NOV-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (229,'БОНДАРЕНКО ПЕТРО ІВАНОВИЧ','Кафедра МП','Доцент',to_date('18-DEC-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (230,'ВАСИЛЕНКО ІВАН ІВАНОВИЧ','Кафедра МП','Професор',to_date('11-FEB-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (231,'ВАСИЛЕНКО СЕРГІЙ ІВАНОВИЧ','Кафедра МП','Старший викладач',to_date('29-JUN-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (232,'ВЕЛИЧКО МИКОЛА ІВАНОВИЧ','Кафедра МП','Асистент',to_date('28-MAR-15','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (233,'ВОЛКОВ ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра МП','Доцент',to_date('13-MAR-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (234,'ВОЛОШИН ВАСИЛЬ ІВАНОВИЧ','Кафедра МП','Професор',to_date('20-JUL-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (235,'ВОЛОШИН МИКОЛА МИКОЛАЙОВИЧ','Кафедра МП','Старший викладач',to_date('27-OCT-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (236,'ГОРДІЄНКО МИКОЛА ІВАНОВИЧ','Кафедра МП','Асистент',to_date('25-DEC-18','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (237,'ГУМЕНЮК МИКОЛА ІВАНОВИЧ','Кафедра МП','Доцент',to_date('06-OCT-19','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (238,'КЛИМЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ІП','Професор',to_date('02-FEB-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (239,'КОВАЛЬ ВІКТОР ВАСИЛЬОВИЧ','Кафедра ІП','Старший викладач',to_date('24-SEP-06','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (240,'КОВАЛЬОВ АНАТОЛІЙ ІВАНОВИЧ','Кафедра ІП','Асистент',to_date('30-JAN-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (241,'КОЛЕСНИК МИКОЛА ІВАНОВИЧ','Кафедра ІП','Доцент',to_date('17-NOV-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (242,'КОСТЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра ІП','Професор',to_date('13-FEB-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (243,'КРАВЧЕНКО АНАТОЛІЙ ВАСИЛЬОВИЧ','Кафедра ІП','Старший викладач',to_date('05-OCT-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (244,'КРАВЧЕНКО МИКОЛА ПЕТРОВИЧ','Кафедра ІП','Асистент',to_date('23-OCT-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (245,'КРАВЧЕНКО МИХАЙЛО ІВАНОВИЧ','Кафедра ІП','Доцент',to_date('19-MAY-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (246,'КРАВЧУК ВОЛОДИМИР ВАСИЛЬОВИЧ','Кафедра ІП','Професор',to_date('07-MAY-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (247,'КУЗЬМЕНКО ОЛЕКСАНДР ВОЛОДИМИРОВИЧ','Кафедра ІП','Старший викладач',to_date('24-MAY-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (248,'МАРТИНЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ІП','Асистент',to_date('23-MAY-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (249,'ОЛІЙНИК АНАТОЛІЙ МИКОЛАЙОВИЧ','Кафедра ІП','Доцент',to_date('23-MAR-92','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (250,'ОЛІЙНИК ВОЛОДИМИР ПЕТРОВИЧ','Кафедра УіФЕБ','Професор',to_date('26-OCT-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (251,'ПАВЛЕНКО АНАТОЛІЙ ІВАНОВИЧ','Кафедра УіФЕБ','Старший викладач',to_date('22-NOV-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (252,'ПАВЛЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра УіФЕБ','Асистент',to_date('30-AUG-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (253,'ПАВЛЮК ВАСИЛЬ ІВАНОВИЧ','Кафедра УіФЕБ','Доцент',to_date('13-MAR-23','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (254,'ПЕТРЕНКО АНАТОЛІЙ ІВАНОВИЧ','Кафедра УіФЕБ','Професор',to_date('07-AUG-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (255,'ПОПОВ МИКОЛА ВАСИЛЬОВИЧ','Кафедра УіФЕБ','Старший викладач',to_date('27-SEP-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (256,'ПОПОВ ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра ЕП','Асистент',to_date('19-OCT-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (257,'РОМАНЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ЕП','Доцент',to_date('22-AUG-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (258,'САВЧЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ЕП','Професор',to_date('26-JAN-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (259,'ТАРАН ВОЛОДИМИР ІВАНОВИЧ','Кафедра ЕП','Старший викладач',to_date('31-MAY-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (1,'Семенько Ольга Вікторівна','Кафедра ПМІ','Доцент',to_date('09-JAN-15','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (2,'Варшамов Ігор Данилович','Кафедра ПМІ','Доцент',to_date('09-JAN-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (3,'Влесенко Петро Ігорович','Кафедра ПМІ','Асистент',to_date('09-FEB-18','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (4,'Кушкін Всеволод Замбехович','Кафедра ПМІ','Професор',to_date('09-JAN-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (5,'Клінський Едуард Володимирович','Кафедра ПМІ','Старший викладач',to_date('09-JAN-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (10,'ВАСИЛЕНКО МИКОЛА ВАСИЛЬОВИЧ','Кафедра АТ','Асистент',to_date('28-APR-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (11,'ЖУК МИКОЛА ІВАНОВИЧ','Кафедра АТ','Доцент',to_date('06-APR-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (12,'ІВАНОВ ВАСИЛЬ ІВАНОВИЧ','Кафедра АТ','Професор',to_date('23-FEB-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (13,'КОВАЛЕНКО МИКОЛА ФЕДОРОВИЧ','Кафедра АТ','Асистент',to_date('31-OCT-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (14,'КОВАЛЬ ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра АТ','Доцент',to_date('07-OCT-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (15,'КОВАЛЬ ІВАН ВАСИЛЬОВИЧ','Кафедра АТ','Професор',to_date('09-DEC-08','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (16,'КОВАЛЬОВ МИКОЛА МИКОЛАЙОВИЧ','Кафедра АТ','Асистент',to_date('18-OCT-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (17,'КОВАЛЬЧУК ВАСИЛЬ МИХАЙЛОВИЧ','Кафедра АТ','Доцент',to_date('20-JUL-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (18,'КОВТУН МИКОЛА ІВАНОВИЧ','Кафедра АТ','Професор',to_date('08-AUG-20','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (19,'КРАВЧЕНКО ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра ГІ','Старший викладач',to_date('02-OCT-93','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (20,'КРАВЧЕНКО ОЛЕКСАНДР ОЛЕКСАНДРОВИЧ','Кафедра ГІ','Асистент',to_date('17-AUG-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (21,'КУЗЬМЕНКО ВАСИЛЬ ІВАНОВИЧ','Кафедра ГІ','Доцент',to_date('22-MAY-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (22,'КУЗЬМЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ГІ','Професор',to_date('28-OCT-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (23,'КУЗЬМЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ГІ','Старший викладач',to_date('11-NOV-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (24,'ЛИТВИНЕНКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ГІ','Асистент',to_date('13-DEC-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (25,'МАРЧЕНКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ГІ','Доцент',to_date('26-APR-23','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (26,'МЕЛЬНИК ВІКТОР ВОЛОДИМИРОВИЧ','Кафедра ГІ','Професор',to_date('23-DEC-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (27,'МЕЛЬНИК ВОЛОДИМИР ОЛЕКСАНДРОВИЧ','Кафедра ГІ','Старший викладач',to_date('23-JAN-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (28,'МЕЛЬНИК ОЛЕКСАНДР АНАТОЛІЙОВИЧ','Кафедра ГІ','Асистент',to_date('15-JUL-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (29,'МОРОЗ ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ГІ','Доцент',to_date('22-MAY-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (30,'ПОЛІЩУК МИКОЛА ВАСИЛЬОВИЧ','Кафедра ГІ','Професор',to_date('19-MAY-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (31,'ПОПОВ ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ГІ','Старший викладач',to_date('07-JAN-92','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (32,'РУДЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ГІ','Асистент',to_date('18-JAN-19','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (33,'ТКАЧЕНКО ОЛЕКСАНДР МИХАЙЛОВИЧ','Кафедра ГІ','Доцент',to_date('22-MAY-19','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (34,'ТКАЧУК ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ГІ','Професор',to_date('11-AUG-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (35,'ХОМЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ГІ','Старший викладач',to_date('15-JUL-15','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (36,'ЧОРНИЙ ВОЛОДИМИР ІВАНОВИЧ','Кафедра РДКК','Асистент',to_date('14-OCT-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (37,'ШЕВЧЕНКО ОЛЕКСАНДР ОЛЕКСАНДРОВИЧ','Кафедра РДКК','Доцент',to_date('30-JAN-92','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (38,'ЩЕРБИНА МИКОЛА ІВАНОВИЧ','Кафедра РДКК','Професор',to_date('27-MAY-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (39,'БІЛИК МИКОЛА ІВАНОВИЧ','Кафедра РДКК','Старший викладач',to_date('18-JAN-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (40,'БОЙКО МИКОЛА ВОЛОДИМИРОВИЧ','Кафедра РДКК','Асистент',to_date('25-MAR-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (41,'БОЙКО МИХАЙЛО ВАСИЛЬОВИЧ','Кафедра РДКК','Доцент',to_date('15-FEB-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (42,'БОНДАР ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра РДКК','Професор',to_date('09-SEP-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (43,'ВАСИЛЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра РДКК','Старший викладач',to_date('11-DEC-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (44,'ВАСИЛЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра РДКК','Асистент',to_date('16-MAY-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (45,'ВЛАСЕНКО МИКОЛА ІВАНОВИЧ','Кафедра РДКК','Доцент',to_date('25-NOV-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (46,'ГАВРИЛЮК МИКОЛА ІВАНОВИЧ','Кафедра РДКК','Професор',to_date('21-JUN-21','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (47,'ЗІНЧЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра РДКК','Старший викладач',to_date('19-JUN-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (48,'ІВАНОВ ВІКТОР МИКОЛАЙОВИЧ','Кафедра РДКК','Асистент',to_date('29-FEB-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (49,'КАРПЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра РДКК','Доцент',to_date('11-JAN-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (50,'КАРПЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра РДКК','Професор',to_date('27-JUL-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (51,'КЛИМЕНКО ВАСИЛЬ ІВАНОВИЧ','Кафедра РДКК','Старший викладач',to_date('31-OCT-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (52,'КОВАЛЬ ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра РДКК','Асистент',to_date('06-NOV-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (53,'КОВАЛЬОВ МИКОЛА ІВАНОВИЧ','Кафедра РДКК','Доцент',to_date('15-JAN-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (54,'КОВАЛЬЧУК МИКОЛА МИХАЙЛОВИЧ','Кафедра РДКК','Професор',to_date('19-JUN-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (55,'КРАВЧЕНКО ІВАН ПЕТРОВИЧ','Кафедра РДКК','Старший викладач',to_date('05-NOV-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (56,'КРАВЧЕНКО МИКОЛА МИХАЙЛОВИЧ','Кафедра УГВОП','Асистент',to_date('16-DEC-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (57,'КРАВЧЕНКО ОЛЕКСАНДР МИХАЙЛОВИЧ','Кафедра УГВОП','Доцент',to_date('23-JUN-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (58,'КРАВЧЕНКО СЕРГІЙ ВОЛОДИМИРОВИЧ','Кафедра УГВОП','Професор',to_date('27-JUN-92','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (59,'МЕЛЬНИК МИКОЛА ОЛЕКСАНДРОВИЧ','Кафедра УГВОП','Старший викладач',to_date('06-SEP-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (60,'МЕЛЬНИК ПЕТРО МИКОЛАЙОВИЧ','Кафедра УГВОП','Асистент',to_date('30-NOV-93','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (61,'ПАВЛЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра УГВОП','Доцент',to_date('24-MAY-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (62,'ПАСІЧНИК ВАЛЕНТИН ГАВРИЛОВИЧ','Кафедра УГВОП','Професор',to_date('19-MAR-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (63,'ПЕТРЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ','Кафедра УГВОП','Старший викладач',to_date('03-JAN-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (64,'ПЕТРЕНКО СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра УГВОП','Асистент',to_date('14-NOV-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (65,'ПЕТРОВ МИКОЛА ІВАНОВИЧ','Кафедра УГВОП','Доцент',to_date('31-MAR-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (66,'ПОПОВ ОЛЕКСАНДР ВОЛОДИМИРОВИЧ','Кафедра УГВОП','Професор',to_date('06-JAN-20','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (67,'САВЧЕНКО ВІКТОР ІВАНОВИЧ','Кафедра УГВОП','Старший викладач',to_date('22-SEP-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (68,'ТИМОШЕНКО МИКОЛА ІВАНОВИЧ','Кафедра УГВОП','Асистент',to_date('09-DEC-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (69,'ТКАЧЕНКО АНАТОЛІЙ ГРИГОРОВИЧ','Кафедра УГВОП','Доцент',to_date('02-MAY-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (70,'ХАРЧЕНКО МИКОЛА ВАСИЛЬОВИЧ','Кафедра АТ','Професор',to_date('11-FEB-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (71,'ШЕВЧЕНКО ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра АТ','Старший викладач',to_date('30-MAY-23','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (72,'ШЕВЧЕНКО ВІКТОР ВОЛОДИМИРОВИЧ','Кафедра АТ','Асистент',to_date('21-JAN-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (73,'ШЕВЧЕНКО ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра АТ','Доцент',to_date('15-SEP-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (74,'ШЕВЧЕНКО ВОЛОДИМИР ОЛЕКСАНДРОВИЧ','Кафедра АТ','Професор',to_date('11-OCT-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (75,'ШЕВЧУК ВОЛОДИМИР ПЕТРОВИЧ','Кафедра АТ','Старший викладач',to_date('21-DEC-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (76,'ЮРЧЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра АТ','Асистент',to_date('12-APR-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (77,'БОЙКО ВОЛОДИМИР ВОЛОДИМИРОВИЧ','Кафедра АТ','Доцент',to_date('04-AUG-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (78,'БОЙЧУК ВАСИЛЬ ІВАНОВИЧ','Кафедра АТ','Професор',to_date('22-MAY-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (79,'БОНДАР МИКОЛА МИКОЛАЙОВИЧ','Кафедра АТ','Старший викладач',to_date('09-APR-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (80,'БОНДАРЕНКО МИКОЛА МИХАЙЛОВИЧ','Кафедра АТ','Асистент',to_date('21-DEC-99','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (81,'БОНДАРЕНКО ОЛЕКСАНДР ГРИГОРОВИЧ','Кафедра АТ','Доцент',to_date('03-OCT-93','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (82,'ВАСИЛЕНКО ВОЛОДИМИР ІВАНОВИЧ','Кафедра АТ','Професор',to_date('01-APR-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (83,'ГАВРИЛЮК ВОЛОДИМИР ВАСИЛЬОВИЧ','Кафедра АТ','Старший викладач',to_date('25-JUN-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (84,'КОВАЛЕНКО АНАТОЛІЙ ВАСИЛЬОВИЧ','Кафедра АТ','Асистент',to_date('26-OCT-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (85,'КОВАЛЕНКО ВАСИЛЬ МИКОЛАЙОВИЧ','Кафедра АТ','Доцент',to_date('02-MAR-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (86,'КОВАЛЕНКО ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра АТ','Професор',to_date('30-OCT-15','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (87,'КОВАЛЕНКО МИКОЛА АНДРІЙОВИЧ','Кафедра АТ','Старший викладач',to_date('22-OCT-90','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (88,'КОВАЛЕНКО СЕРГІЙ ОЛЕКСАНДРОВИЧ','Кафедра ПД','Асистент',to_date('23-JUL-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (89,'КОВАЛЬ ВАСИЛЬ ПЕТРОВИЧ','Кафедра ПД','Доцент',to_date('13-JAN-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (90,'КОВАЛЬ ОЛЕКСАНДР ВОЛОДИМИРОВИЧ','Кафедра ПД','Професор',to_date('10-JUN-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (91,'КОВАЛЬЧУК ВОЛОДИМИР МИХАЙЛОВИЧ','Кафедра ПД','Старший викладач',to_date('01-JUL-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (92,'КРАВЧЕНКО ВАСИЛЬ ВАСИЛЬОВИЧ','Кафедра ПД','Асистент',to_date('31-JUL-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (93,'КУШНІР ВОЛОДИМИР ІВАНОВИЧ','Кафедра ПД','Доцент',to_date('13-JUL-20','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (94,'ЛИСЕНКО МИКОЛА ПЕТРОВИЧ','Кафедра ПД','Професор',to_date('07-FEB-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (95,'МАРТИНЮК МИКОЛА ВАСИЛЬОВИЧ','Кафедра ПД','Старший викладач',to_date('26-JUN-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (96,'МАРЧЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ПД','Асистент',to_date('25-JUL-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (97,'МЕЛЬНИК ВАСИЛЬ ВОЛОДИМИРОВИЧ','Кафедра ПД','Доцент',to_date('25-SEP-05','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (98,'МЕЛЬНИК ВАСИЛЬ ФЕДОРОВИЧ','Кафедра ПД','Професор',to_date('23-DEC-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (99,'МЕЛЬНИК МИХАЙЛО МИКОЛАЙОВИЧ','Кафедра ПД','Старший викладач',to_date('12-MAY-19','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (100,'МИХАЙЛЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ПД','Асистент',to_date('08-OCT-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (101,'МОРОЗ ОЛЕКСАНДР ВАСИЛЬОВИЧ','Кафедра ПД','Доцент',to_date('03-AUG-02','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (102,'ОЛІЙНИК ВІКТОР МИКОЛАЙОВИЧ','Кафедра ПД','Професор',to_date('05-SEP-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (103,'ПАНЧЕНКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ПД','Старший викладач',to_date('29-SEP-04','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (104,'ПЕТРЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ПД','Асистент',to_date('26-JAN-09','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (105,'ПОЛІЩУК ВІКТОР ІВАНОВИЧ','Кафедра ЕІ','Доцент',to_date('14-AUG-01','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (106,'ПОЛІЩУК СЕРГІЙ МИКОЛАЙОВИЧ','Кафедра ЕІ','Професор',to_date('18-SEP-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (107,'ПОНОМАРЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ЕІ','Старший викладач',to_date('09-MAY-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (108,'СЕМЕНЮК ВАСИЛЬ ІВАНОВИЧ','Кафедра ЕІ','Асистент',to_date('26-DEC-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (109,'СЕРГІЄНКО МИКОЛА ІВАНОВИЧ','Кафедра ЕІ','Доцент',to_date('20-NOV-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (110,'ТКАЧЕНКО ВАСИЛЬ МИКОЛАЙОВИЧ','Кафедра ЕІ','Професор',to_date('17-AUG-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (111,'ТКАЧЕНКО ВОЛОДИМИР ОЛЕКСАНДРОВИЧ','Кафедра ЕІ','Старший викладач',to_date('23-MAR-12','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (112,'ТКАЧЕНКО МИКОЛА ГРИГОРОВИЧ','Кафедра ЕІ','Асистент',to_date('03-FEB-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (113,'ТКАЧУК АНАТОЛІЙ ІВАНОВИЧ','Кафедра ЕІ','Доцент',to_date('19-OCT-89','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (114,'ТКАЧУК ВАСИЛЬ МИКОЛАЙОВИЧ','Кафедра ЕІ','Професор',to_date('27-JAN-13','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (115,'ХАРЧЕНКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ЕІ','Старший викладач',to_date('10-JAN-11','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (116,'ХОМЕНКО МИКОЛА МИКОЛАЙОВИЧ','Кафедра ЕІ','Асистент',to_date('20-SEP-93','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (117,'ЧОРНИЙ ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ЕІ','Доцент',to_date('07-MAY-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (118,'ШЕВЧЕНКО ІВАН МИКОЛАЙОВИЧ','Кафедра ЕІ','Професор',to_date('04-MAR-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (119,'ШЕВЧЕНКО ІВАН МИХАЙЛОВИЧ','Кафедра ЕІ','Старший викладач',to_date('02-MAR-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (120,'ШЕВЧЕНКО МИКОЛА ОЛЕКСІЙОВИЧ','Кафедра ЕІ','Асистент',to_date('02-DEC-07','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (121,'ШЕВЧУК ВАСИЛЬ ПЕТРОВИЧ','Кафедра ЕІ','Доцент',to_date('24-AUG-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (122,'ШЕВЧУК ПЕТРО ІВАНОВИЧ','Кафедра ЕТ','Професор',to_date('01-MAR-00','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (123,'ЯРОШЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ЕТ','Старший викладач',to_date('11-JUN-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (124,'БАБИЧ МИКОЛА ІВАНОВИЧ','Кафедра ЕТ','Асистент',to_date('28-OCT-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (125,'БОЙКО ПЕТРО ВАСИЛЬОВИЧ','Кафедра ЕТ','Доцент',to_date('23-OCT-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (126,'БОНДАРЕНКО ВОЛОДИМИР ВОЛОДИМИРОВИЧ','Кафедра ЕТ','Професор',to_date('12-APR-14','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (127,'БОНДАРЕНКО СЕРГІЙ ВАСИЛЬОВИЧ','Кафедра ЕТ','Старший викладач',to_date('06-SEP-95','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (128,'ГАВРИЛЮК ВАСИЛЬ ІВАНОВИЧ','Кафедра ЕТ','Асистент',to_date('02-JUN-96','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (129,'ГОНЧАРОВ МИКОЛА ІВАНОВИЧ','Кафедра ЕТ','Доцент',to_date('10-APR-93','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (130,'ДОРОШЕНКО МИКОЛА ІВАНОВИЧ','Кафедра ЕТ','Професор',to_date('08-APR-19','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (131,'ІВАНОВ АНАТОЛІЙ ІВАНОВИЧ','Кафедра ЕТ','Старший викладач',to_date('10-SEP-97','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (132,'ІВАНОВ ВОЛОДИМИР ОЛЕКСАНДРОВИЧ','Кафедра ЕТ','Асистент',to_date('09-APR-98','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (133,'КОВАЛЕНКО ІВАН ГРИГОРОВИЧ','Кафедра ЕТ','Доцент',to_date('17-MAR-94','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (134,'КОВАЛЕНКО ЮРІЙ ІВАНОВИЧ','Кафедра ЕТ','Професор',to_date('30-JAN-16','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (135,'КОВАЛЬЧУК ВОЛОДИМИР ПЕТРОВИЧ','Кафедра ЕТ','Старший викладач',to_date('12-FEB-91','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (136,'КОЛОМІЄЦЬ МИКОЛА ВАСИЛЬОВИЧ','Кафедра ЕТ','Асистент',to_date('12-APR-17','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (137,'КРАВЕЦЬ ВОЛОДИМИР ІВАНОВИЧ','Кафедра ЕТ','Доцент',to_date('05-DEC-22','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (138,'ЛЕВЧЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ЕТ','Професор',to_date('29-MAR-03','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (139,'ЛИСЕНКО ОЛЕКСАНДР ІВАНОВИЧ','Кафедра ЕТ','Старший викладач',to_date('27-APR-20','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (140,'ЛИТВИНЕНКО ВІКТОР ІВАНОВИЧ','Кафедра ЕТ','Асистент',to_date('20-JUL-10','DD-MON-RR'));
Insert into ARGUS.TEACHER (TEACHER_ID,TEACHER_NAME,DEPT_NAME,TEACHER_POSITION,DATE_HIRE) values (141,'ЛИТВИНЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ','Кафедра ЕТ','Доцент',to_date('03-DEC-12','DD-MON-RR'));
