REM INSERTING into ARGUS.UPLAN
SET DEFINE OFF;
Insert into ARGUS.UPLAN (SUBJECT_ID,SEMESTR_ID,WORK_ID,GROUP_ID,TEACHER_ID,Q_HOURS) values (1,1,1,1,2,150);
Insert into ARGUS.UPLAN (SUBJECT_ID,SEMESTR_ID,WORK_ID,GROUP_ID,TEACHER_ID,Q_HOURS) values (2,3,1,3,2,150);
Insert into ARGUS.UPLAN (SUBJECT_ID,SEMESTR_ID,WORK_ID,GROUP_ID,TEACHER_ID,Q_HOURS) values (3,3,2,2,1,90);
