--------------------------------------------------------
--  Ref Constraints for Table UPLAN
--------------------------------------------------------

  ALTER TABLE "ARGUS"."UPLAN" ADD CONSTRAINT "UPLAN_CON_FK_SUBJ_ID" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "ARGUS"."SUBJECT" ("SUBJECT_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."UPLAN" ADD CONSTRAINT "UPLAN_CON_FK_SEM_ID" FOREIGN KEY ("SEMESTR_ID")
	  REFERENCES "ARGUS"."SEMESTR" ("SEMESTR_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."UPLAN" ADD CONSTRAINT "UPLAN_CON_FK_GR_ID" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "ARGUS"."SGROUP" ("GROUP_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."UPLAN" ADD CONSTRAINT "UPLAN_CON_FK_WORK_ID" FOREIGN KEY ("WORK_ID")
	  REFERENCES "ARGUS"."WORK" ("WORK_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ARGUS"."UPLAN" ADD CONSTRAINT "UPLAN_CON_FK_TCHR_ID" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "ARGUS"."TEACHER" ("TEACHER_ID") ON DELETE SET NULL ENABLE;
